### ISSUE TITLE
Create Home page

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#174]
<img width="888" alt="Screenshot 2021-06-02 at 21 13 04" src="https://user-images.githubusercontent.com/6358755/120538910-553f3700-c3e7-11eb-8cdf-b8dcabb1d427.png">

need to move this page: https://www.myprofile.pro/ to the new project

- [x] https://github.com/eerison/myprofile/pull/430 Create a base layout to home page 
- [x] #431
- [x] #432
- [x] #433
- [x] #434
- [x] #468
- [ ] #469
- [x] #502 Created endpoint to register
- [x] Created endponit to login
- [ ] #509
- [x] #484
- [x] #517
- [ ] #529
- [ ] #530
- [x] #543
- [ ] after finish whole feature, check if there is a good coverage to home page to avoid something break the page.

**Comment by eerison** [comment]
Back-end card : https://github.com/eerison/myprofile/issues/175

**Comment by eerison** [comment]
related with #322

**Comment by eerison** [comment]
<img width="1792" alt="Screenshot 2021-07-01 at 14 56 09" src="https://user-images.githubusercontent.com/6358755/124128688-4c409480-da7d-11eb-919b-5d3330921f49.png">

created a base homepage layout
