### ISSUE TITLE
Deployment using Docker and CircleCi

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#202]
Now we're using Heroku to deploy everything and the Idea is migrate to Circle CI using Docker too

- [ ] #291 now when Open a PR heroku add a new enverioment with PR's code, and basically I want to do the same.
- [ ] #292 after the branch going to be merged, the master branch must be deployed to stage
- [ ] #293 after create a realease need to activate a step to deploy to prod (manual for now)
- [ ] #294 create a step to create a release in [sentry](https://www.sentry.io)

Those issues must be finish in this order   
https://github.com/apache/openwhisk-runtime-php

**Comment by eerison** [comment]
It was resolved in version 2.6.0
