### ISSUE TITLE
Migrate to symfony 5

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#278]
- [x] #306 migrate to Symfony 5.2.0-RC-2
- [x] #313 migrate to Symfony 5.2
- [x] #325 migrate to Symfony 5.2.1
- [x] #346  migrate to Symfony 5.2.2
- [x] #435 migrate to Symfony 5.3
- [ ] migrate to Symfony 5.4 LTS

**Comment by eerison** [comment]
to migrate to Symfony 5, need to remove FosUserBundle first #284

**Comment by eerison** [comment]
Need to fix this: https://github.com/symfony/symfony/issues/39120

**Comment by eerison** [comment]
it's already using 5.4-dev, then it's ok for now ;)
