### ISSUE TITLE
SF5

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#312]
- [x] PHP
- [x] **[HTTP](https://symfony.com/doc/current/http_client.html)**
  - [x] Client / Server interaction
  - [x] Status codes
  - [x] HTTP request
  - [x] HTTP response
  - [x] HTTP methods
  - [x] Cookies
  - [x] Caching
  - [x] Content negotiation
  - [x] Language detection
  - [x] Symfony HttpClient component
- [x] Symfony Architecture
  - [x] Symfony Flex
  - [x] License
  - [x] Components
  - [x] Bridges
  - [x] Code organization
  - [x] Request handling
  - [x] Exception handling
  - [x] Event dispatcher and kernel events
  - [x] Official best practices - #327 #328 
  - [x] Release management
     ```
      Starting from the Symfony 3.x branch, the number of minor versions is limited to five per branch 
      (X.0, X.1, X.2, X.3 and X.4).
     The last minor version of a branch (e.g. 4.4, 5.4) is considered a long-term support version 
     and the other ones are considered standard versions:
     ```
  - [x] Backward compatibility promise
  - [x] Deprecations best practices
  ```
  trigger_deprecation
  @ deprecated
  ```
  - [x] Framework overloading
  - [x] Release management and roadmap schedule
  - [x] Framework interoperability and PSRs
  - [x] Naming conventions
- [x] Controllers
  ```
  use Symfony\Bundle\FrameworkBundle\Controller\AbstractController
  ```
  - [x] Naming conventions
  - [x] The base AbstractController class
  - [x] The request
  - [x] The response
  ````
  use Symfony\Component\HttpFoundation\Request;
  use Symfony\Component\HttpFoundation\Response;
  ````
  - [x] The cookies
  ```php
  $request->cookies
  ```
  - [x] The session
  ````
  use Symfony\Component\HttpFoundation\Session\SessionInterface;
  ````
  - [x] The flash messages
  - [x] HTTP redirects
  - [x] Internal redirects
  - [x] Generate 404 pages
  - [x] File upload
  ```php
  $request->files
  ```
  - [x] Built-in internal controllers
- [x] Routing #333 
  ```php
  use Symfony\Component\Routing\Annotation\Route
   /**
     * @Route("/blog", name="blog_list")
     */
  ```
  - [x] Configuration (YAML, XML, PHP & annotations)
  - [x] Restrict URL parameters
  - [x] Set default values to URL parameters
  - [x] Generate URL parameters
  - [x] Trigger redirects
  - [x] Special internal routing attributes
  - [x] Domain name matching
  - [x] Conditional request matching
  - [x] HTTP methods matching
  - [x] User's locale guessing
  - [x] Router debugging
- [x] Templating with Twig
  - [x] Auto escaping
  - [x] Template inheritance
  - [x] Global variables
  - [x] Filters and functions
  - [x] Template includes
  - [x] Loops and conditions
  - [x] URLs generation
  - [x] Controller rendering
  - [x] Translations and pluralization
  - [x] String interpolation
  - [x] Assets management
  - [x] Debugging variables
- [x] Forms
  - [x] Forms creation
  - [x] Forms handling
  - [x] Form types
  - [x] Forms rendering with Twig
  - [x] Forms theming
  - [x] CSRF protection #335 
  - [x] Handling file upload
  - [x] Built-in form types
  - [x] Data transformers
  ```php
  $builder->get('tags')
            ->addModelTransformer(new CallbackTransformer(
                function ($tagsAsArray) {
                    // transform the array to a string
                    return implode(', ', $tagsAsArray);
                },
                function ($tagsAsString) {
                    // transform the string back to an array
                    return explode(', ', $tagsAsString);
                }
            ))
  ```
  - [x] Form events
  ```php
  use Symfony\Component\Form\FormEvent;
  use Symfony\Component\Form\FormEvents;

  $listener = function (FormEvent $event) {
    // ...
  };

  $form = $formFactory->createBuilder()
    // ... add form fields
    ->addEventListener(FormEvents::PRE_SUBMIT, $listener);
  ```
  ```
  During FormEvents::PRE_SET_DATA, Form::setData() is locked and will throw an exception if used.
  If you wish to modify data, you should use FormEvent::setData() instead.
  ```
  
<img width="718" alt="Screenshot 2020-12-25 at 21 07 23" src="https://user-images.githubusercontent.com/6358755/103141492-3b415000-46f5-11eb-9c58-0b155a400af8.png">

  - [x] Form type extensions
  ```php
  use Symfony\Component\Form\AbstractTypeExtension;
  ```
- [x] Data Validation
  ```
  use Symfony\Component\Validator\Constraints as Assert;
  use Symfony\Component\Validator\Validator\ValidatorInterface;
  
  /*
         * Uses a __toString method on the $errors variable which is a
         * ConstraintViolationList object. This gives us a nice string
         * for debugging.
         */
        $errorsString = (string) $errors;
        
        /**
     * @Assert\Choice(
     *     choices = { "fiction", "non-fiction" },
     *     message = "Choose a valid genre."
     * )
     */
    private $genre;

  ```
  ```
   /**
     * @Assert\NotBlank(message="author.name.not_blank")
     */
    public $name;
    
    ...
    # translations/validators.en.yaml
    author.name.not_blank: Please enter an author name.
  ```
  - [x] PHP object validation
  - [x] Built-in validation constraints
  - [x] Validation scopes
    ```
    use Symfony\Component\Validator\Constraint;
    use Symfony\Component\Validator\ConstraintValidator;
    ```
  - [x] Validation groups
  ```
  $errors = $validator->validate($author, null, ['registration']);
  /**
     * @Assert\NotBlank(groups={"registration"})
     * @Assert\Length(min=7, groups={"registration"})
     */
    private $password;
  ```
  - [x] Group sequence
  ```
  /**
  * @Assert\GroupSequence({"User", "Strict"})
  */
  class 
  ```
  - [x] Custom callback validators
  ```
   use Symfony\Component\Validator\Context\ExecutionContextInterface;
  
    /**
     * @Assert\Callback
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        // ...
    }
    
    //or to static validate
    use Symfony\Component\Validator\Constraints as Assert;

   /**
    * @Assert\Callback({"Acme\Validator", "validate"})
    */
    class Author
    {
    }
  ```
  - [x] Violations builder
- [x] Dependency Injection
  services.yaml
  ```yaml
  _defaults:
      autowire: true
      autoconfigure: true
  ```
  - [x] Service container
  - [x] Built-in services
  - [x] Configuration parameters
    ```
    php bin/console debug:container --env-vars
    php bin/console debug:container --env-var=FOO
    php bin/console debug:container --parameters
    ```
  - [x] Services registration
  - [x] Tags
  ````
  App\Handler\Two:
        tags: ['app.handler']

    App\HandlerCollection:
        # inject all services tagged with app.handler as first argument
        arguments:
            - !tagged_iterator app.handler
            
    public function __construct(iterable $handlers)
  ````
  priotiry
  ```
  App\Handler\One:
        tags:
            - { name: 'app.handler', priority: 20 }
            
   # or -----
       public static function getDefaultPriority(): int
    {
        return 3;
    }
    
    App\HandlerCollection:
        # inject all services tagged with app.handler as first argument
        arguments:
            - !tagged_iterator { tag: app.handler, default_priority_method: getPriority }
  ```
  key
  ```
  services:
    App\Handler\One:
        tags:
            - { name: 'app.handler', key: 'handler_one' }

    App\Handler\Two:
        tags:
            - { name: 'app.handler', key: 'handler_two' }

    App\HandlerCollection:
        arguments: [!tagged_iterator { tag: 'app.handler', index_by: 'key' }]
        
   namespace App\Handler;

  class HandlerCollection
  {
    public function __construct(iterable $handlers)
    {
        $handlers = iterator_to_array($handlers);

        $handlerTwo = $handlers['handler_two'];
    }
  }
  
  # or ----
  namespace App\Handler;

  class One
  {
    // ...
    public static function getDefaultIndexName(): string
    {
        return 'handler_one';
    }
  }
  
  

   App\HandlerCollection: 
   # use getIndex() instead of getDefaultIndexName() 
   arguments: [!tagged_iterator { tag: 'app.handler', default_index_method: 'getIndex' }]
  ```
  - [x] Semantic configuration
  - [x] Factories
  - [x] Compiler passes
  - [x] Services autowiring
- [x] Security
  - [x] Authentication
  - [x] Authorization
  - [x] Configuration
  - [x] Providers
  security.yaml
  ```
  security:
    providers:
        # the name of your user provider can be anything
        your_custom_user_provider:
            id: App\Security\UserProvider
  ```
  - [x] Firewalls
    ```
    security:
    firewalls:
        secured_area:
            pattern: ^/admin
    ```
  - [x] Users
  - [x] Passwords encoders
  ```
  security:
    # ...
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 12
  ```
  ```php
  namespace App\Entity;

  use Symfony\Component\Security\Core\Encoder\EncoderAwareInterface;
  use Symfony\Component\Security\Core\User\UserInterface;

  class User implements UserInterface, EncoderAwareInterface
  {
    public function getEncoderName()
    {
        if ($this->isAdmin()) {
            return 'harsh';
        }

        return null; // use the default encoder
    }
  }
  ```
  ```
  security:
    # ...
    encoders:
        app_encoder:
            id: 'App\Security\Encoder\MyCustomPasswordEncoder'
  ```
  - [x] Roles
  - [x] Access Control Rules
  - [x] Guard authenticators
  - [x] Voters and voting strategies #339
  ```
  use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
  @IsGranted("ROLE_USER", attributes="owner", subject="certification")
  ```
  [example](https://github.com/eerison/myprofile/blob/master/src/Security/OwnerVoter.php)
- [x] HTTP Caching
  ```php
  use Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache;
  
  class CacheKernel extends HttpCache
  ```
  PSR-6
  - [x] Cache types (browser, proxies and reverse-proxies)
  - [x] Expiration (Expires, Cache-Control)
  - [x] Validation (ETag, Last-Modified)
  - [x] Client side caching
  - [x] Server side caching
  - [x] Edge Side Includes
- [x] Console
  ```php
  use Symfony\Component\Console\Command\Command
  use Symfony\Component\Console\Input\InputInterface;
  use Symfony\Component\Console\Output\OutputInterface;
  ```
  - [x] Built-in commands
  - [x] Custom commands
  - [x] Configuration
  - [x] Options and arguments
  ```php
  use Symfony\Component\Console\Input\InputArgument;
  use Symfony\Component\Console\Command\Command;
  use Symfony\Component\Console\Input\InputInterface;
  use Symfony\Component\Console\Output\OutputInterface;

  
  protected function configure()
    {
        $this
            ->setDescription('Creates a new user.')
            ->setHelp('This command allows you to create a user...')
            ->addArgument('password', $this->requirePassword ? InputArgument::REQUIRED : InputArgument::OPTIONAL, 'User password')
        ;
    }
  ```
  
  ```php
  
    use Symfony\Component\Console\Input\InputOption;

    $this
        ->addOption(
            'iterations',
            null,
            InputOption::VALUE_REQUIRED,
            'How many times should the message be printed?',
            1
        )
    ;
  ```
  - [x] Input and Output objects
  - [x] Built-in helpers
    ```
    Formatter Helper
    Process Helper
    Progress Bar
    Question Helper
    Table
     Debug Formatter Helper
    ```
  - [x] Console events
  - [x] Verbosity levels
  ``` php
  # increase verbosity of message
  php bin/console some-command -v

  # also informative messae
  php bin/console some-command -vv

  # all messages
  php bin/console some-command -vvv
  ```
  
<img width="707" alt="Screenshot 2020-12-23 at 12 57 26" src="https://user-images.githubusercontent.com/6358755/102993976-75a4c480-451e-11eb-9eb6-6e67a54e898b.png">

- [x] **[Automated Tests](https://symfony.com/doc/current/testing.html)**
  - [x] #314 Unit tests with PHPUnit
  - [x] #314 Functional tests with PHPUnit
  - [x] #314 Client object
  - [x] #314 Crawler object
  - [x] #314 Profile object
  - [x] Framework objects access
  - [x] Client configuration
  - [x] Request and response objects introspection
  - [x] PHPUnit bridge
  - [x] Handling legacy deprecated code ([link1](https://symfony.com/blog/new-in-symfony-3-1-deprecation-helper-improvements))
- [x] Miscellaneous
   - [x] Configuration (including DotEnv and ExpressionLanguage components)
   - [x] Error handling
   - [x] Code debugging
   - [x] Deployment best practices
   - [x] [Process and Serializer components](https://symfony.com/doc/current/components/serializer.html) (https://github.com/transloadit/php-sdk/pull/35)
   - [x] Messenger component
   - [x] Mime and Mailer components
   ```
   use Symfony\Component\Mailer\MailerInterface;
   use Symfony\Component\Mime\Email;
   
   // config
   framework:
    mailer:
        dsn: 'null://null'
        transports:
            main: '%env(MAILER_DSN)%'
            alternative: '%env(MAILER_DSN_IMPORTANT)%'
        envelope:
            recipients: ['youremail@example.com']
   ```
   - [x] Filesystem and Finder components
   - [x] Lock component
   - [x] Web Profiler, Web Debug Toolbar and Data collectors
   - [x] Internationalization and localization (and Intl component)
- [ ] **Extra content 😄 (see later)**  
   - [ ] [Test Mailer](https://symfony.com/doc/current/testing/functional_tests_assertions.html#mailer)
